### ISSUE TITLE
Supporting the barcode field on products/variants

### ISSUE THREAD

**Issue by lsirivong** [wombat/shopify_integration#1]
We will be adding a barcode field to products which we'd like to sync across our integrations. If we want this field to be sent to shopify (it appears to be [supported in the API](https://docs.shopify.com/api/product_variant#barcode-property)), is this something that would require a PR / fork or is it supported currently? I'm trying to grok the [variant.rb code](https://github.com/wombat/shopify_integration/blob/173eaca8ef73fc3083585bdae00651bab2559241/lib/variant.rb#L64-L68) and am I correct that the only fields are `price`, `sku`, and `option`s are sent to Shopify?

**Comment by phstc** [comment]
Hey @lsirivong 

You are right, it will require a PR and should be optional so it would not fail for customers that aren't using it.
